### ISSUE TITLE
Add instructions to readme

### ISSUE THREAD

**Issue by blaggacao** [OCA/queue#104]
You definitely want to consider adding stable and canonical usage instructions to the readme.
Could you? @guewen

**Comment by blaggacao** [comment]
I'm considering incorporating it into the [Odoo-Operator](https://xoe-labs.github.io/odoo-operator/) stack. Background jobs are a useful thing at times...

**Comment by blaggacao** [comment]
Or do a Hugo project site like this: https://camptocamp.github.io/bivac/

@raphink might help?

**Comment by guewen** [comment]
Docs definitely need some :heart:

**Comment by blaggacao** [comment]
@guewen How would I run the `JobRunner` standalone (I mean the workhorse, not the scheduler - it seems the `jubrunner` folder naming is irritating here referring to the scheduler)? That is: 

- Without Odoo-gevented-worker 
- Without Odoo-HTTWorkers and 
- Without Odoo-CronWorkers

**Comment by blaggacao** [comment]
Is there a jobrunner wsgi component or such or a command line shortcut?
