### ISSUE TITLE
Make relation of jobs

### ISSUE THREAD

**Issue by etobella** [OCA/queue#109]
Sometimes the job execution should wait for another job to finish. 
It could be interesting to make a field `wait_for_job_ids` on job and only start when all the wait for jobs has finished. What do you think?
I can make the PR if you are interested.

**Comment by sbidoul** [comment]
Have you considered using sequential channels for this?

**Comment by simahawk** [comment]
I agree w/ @sbidoul : you can have a channel w/ job capacity 1 -> all the jobs we'll wait for the current one to finish.
@etobella do you have a particular use case where this may not work?

**Comment by sbidoul** [comment]
Not only capacity 1 but also sequential (which stops on errored jobs).

**Comment by etobella** [comment]
Uff, that may be a problem...
If it is sequential it may affect unrelated records.
I will put an example:
I export `sale.order` and `sale.order.line`. If I export them on create with the current job_queue, I may export first the `sale.order.line` and this may be a consistency problem, just for a few ms, but that will make the job fail. If I use your proposal and the job fails, no sale order will be exported until the record is fixed and that may be a problem for the users of the system that receives the data.

**Comment by sbidoul** [comment]
@etobella jobs only start after the end of the current transaction. So if you create order and order lines, as well as export jobs in the same transactions, it will work.

**Comment by etobella** [comment]
I will review it, but I don't like the idea of capacity 1

**Comment by sbidoul** [comment]
Or you create a job that exports the order, which itself creates one job for each line (if I understand your use case correctly).

**Comment by sbidoul** [comment]
So you don't need capacity 1

**Comment by etobella** [comment]
`sale.order` was an example, It is currently a more complex background of elements that could include several options and a less strict relation (the childs could exist without the parent record). :cry:
The only option I find is to add the related job on the function and check it on the export

**Comment by guewen** [comment]
> The only option I find is to add the related job on the function and check it on the export

Well performance-wise this will not be very good. Actually I have some ideas on how we can implement dependencies between jobs without too much hassle and adding no additional penalty for jobs not using it. I'll try to write a prototype soon.

**Comment by pedrobaeza** [comment]
Any news on this?

**Comment by guewen** [comment]
Did not have time, I'll try to write a draft (I would so much love to have some time to work on that though) for the implementation I was thinking about. Some details may be inaccurate as I didn't verify all my assumptions.

I extracted my draft here: https://github.com/OCA/queue/issues/129

**Comment by guewen** [comment]
Tracked on #129
