### ISSUE TITLE
No timeout for queue job

### ISSUE THREAD

**Issue by nguyenducthuanuet** [OCA/queue#110]
Hi everyone, I have a problem with queue job. My job spent too much time and it always remains on 'Started' state. So I can't run other jobs.
So can I set timeout for my job ? Or can we solve this problem by another way ?
Thank you.

**Comment by guewen** [comment]
What is doing your job exactly? Example: if your job executes a requests to another server, be sure to set a timeout in your call.
Jobs have no timeout, although you can have more than one workers executing jobs, and you should probably put your heavy job in a dedicated channel, so it won't block the other jobs.

**Comment by nguyenducthuanuet** [comment]
My job sends a message to RabbitMQ Server via rabbitpy library (https://github.com/gmr/rabbitpy). My problem occured when I config v-host not correctly and rabbitby doesn't release the process so my job remain 'Started' forever. Therefore, I think queue should have timeout for each, after timeout job will be 'Failed', because the next job can work with that config. (Now, my next job can't execute because the maximum of concurrent job in my channel is 2 and there are 2 jobs with forever state 'Started' by that problem),

**Comment by guewen** [comment]
> My problem occured when I config v-host not correctly and rabbitby doesn't release the process so my job remain 'Started' forever.

So this is unrelated to the job queue, if the rabbitpy lib handles a timeout, it means at some point it will raises a kind of timeout error which will be propagated to the job handler, then either you let it bubble up and the job will be failed, either you catch it and raise a RetryableJobError so the job is retried later. In any case, to me it's a problem with rabbitpy not having a timeout configured. Never used this lib but it seems possible: https://github.com/gmr/rabbitpy/pull/85
