### ISSUE TITLE
A question about job id

### ISSUE THREAD

**Issue by burinov** [OCA/queue#116]
In this example how do I know `uuid` of `queue.job` record, so I can use it in `MyModel.my_method` call?

```
from odoo import models, fields, api
from odoo.addons.queue_job.job import job

class MyModel(models.Model):
   _name = 'my.model'

   @api.multi
   @job
   def my_method(self, a, k=None):
       _logger.info('executed with a: %s and k: %s', a, k)


class MyOtherModel(models.Model):
    _name = 'my.other.model'

    @api.multi
    def button_do_stuff(self):
        self.env['my.model'].with_delay().my_method('a', k=2)
```

I want to be able to link objects and all jobs related to them.

Thank you!

**Comment by guewen** [comment]
You shouldn't need to know the job id, from `my_method`, you can access to the user(s) using `self`.

**Comment by minimedj** [comment]
@guewen In case I want to link all job records to MyModel, so I can analyse them later. How do I do it?

**Comment by guewen** [comment]
When you call `with_delay()`, it returns the job that you can link then to records. Not sure what you mean by "analyse them later" though.

**Comment by minimedj** [comment]
"analyse them later" means that in case I put SMS sending to the queue I want to see which users didn't get messages. It is just an example.

@guewen Could you please show how to use `with_delay()` to link jobs to my model?

**Comment by guewen** [comment]
I think you shouldn't rely on the queue_job records for that. They represent an async execution of a method, they do not represent "a SMS being sent or not", consider that a job can be duplicated, requeued, is dropped after X days (30 by default). My design would be to have a table for SMS to send, each record being for instance `(partner_id, state)` or `(partner_id, sent)`, then from this model, you can delay whatever background execution you want. The state "sent or not" is tracked on the sms table. If you have 2 jobs for the same SMS or requeue a job, the second execution will check the state from this sms table, in the case it has already been sent, will do nothing.

**Comment by minimedj** [comment]
@guewen Thank you for you feedback. Will think about your idea. p.s. At the moment I use celery queue.

**Comment by guewen** [comment]
> use celery queue.

So you get the point that you wouldn't reference a celery job in from an odoo model, think the same about odoo queue jobs ;)

**Comment by minimedj** [comment]
@guewen I will refer, because I need it for accounting. see: each SMS transaction costs money. I send a lot of SMS. About 5% of them are not delivered but charged by our SMS gateway. If I can build a report about this data I get a refund. So, I need link stuff.

I understand your approach but it is not applicable for me. It is kind of workaround with lost context for my case. I will parch celery solution for my needs.
