### ISSUE TITLE
[11] Job queues not running, stuck on pending

### ISSUE THREAD

**Issue by JesperAm** [OCA/queue#125]
I've been trying to run the Asynchronous Import module to import a large amount of products into our Odoo 11 database for a customer. Problem is, the job just stays at pending and even after reading the GitHub and Odoo Apps page have been unable to grasp the reason why it isn't running.

The wiki / usage pages don't have much in the way of instructions so I assume there isn't much that needs configuring for it to work out of the box? Or am I way in over my head trying to use this module? I'm stuck and would really appreciate some help!

**Comment by guewen** [comment]
`queue_job` must be in `--load` or `SERVER_WIDE_MODULES`.

Suggested reading if not yet done: http://odoo-connector.com/guides/jobrunner.html

**Comment by rvalyi** [comment]
gah that ```--load=queue_job``` thing is easily forgotten... And then even me was banging my head against the wall several hours to figure out why the damn job wouldn't start...

**Comment by leonelfolmer** [comment]
Hi @rvalyi, seems you already solve the problem. Can you please help me out with that? Im still stuck. Trying to install Jira Connector but the jobs are not running. What exactly you do?    

Im trying to edit my odoo-server.log file but not work:

`[options]`
`; This is the password that allows database operations:`
`admin_passwd = admin`
`xmlrpc_port = 8069`
`logfile = /var/log/odoo/odoo-server.log`

`workers = 4`
`server_wide_modules = queue_job`

`[queue_job]`
`channels = root:1,root.connector_jira.import:2`

**Comment by guewen** [comment]
@leonelfolmer can you try with `root:2,root:connector_jira:2,root.connector_jira.import:2`? I wonder if it doesn't default `root:connector_jira` to 0 if not declared. 

Side note: it does not make sense to set 2 slots in the channel `root.connector_jira.import` if the root channel has 1 slot, either set 2 slots in root, or set 1 slot in `root.connector_jira.import`.

**Comment by leonelfolmer** [comment]
Thank you for your time @guewen and sorry for my late response. it´s working now. I have all jobs running but nothing importing from Jira to Odoo Projects.  

In some jobs I got this exception:

` jira_key = assignee['key']
KeyError: 'key'`
