### ISSUE TITLE
Facing error with multi database instance

### ISSUE THREAD

**Issue by foutoucour** [OCA/queue#153]
Hello,

We are happy to use `queue_job` here at Numigi. It works very well in most of cases, but we are facing some errors when it comes to an instance that has more than one database and `queue_job` installed on several of them.

```
odoo_1  | 2019-07-03 10:03:55,876 1 INFO ? odoo.addons.queue_job.jobrunner.runner: initializing database connections
odoo_1  | 2019-07-03 10:03:55,901 1 INFO ? odoo.addons.queue_job.jobrunner.runner: queue job runner ready for db test_20190531_2018
odoo_1  | 2019-07-03 10:03:55,955 1 INFO ? odoo.addons.queue_job.jobrunner.runner: queue job runner ready for db test_20190621_1613
odoo_1  | 2019-07-03 10:03:55,973 1 ERROR ? odoo.addons.queue_job.jobrunner.runner: exception: sleeping 5s and retrying
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/mnt/third-party-addons/queue_job/jobrunner/runner.py", line 476, in run
odoo_1  |     self.initialize_databases()
odoo_1  |   File "/mnt/third-party-addons/queue_job/jobrunner/runner.py", line 398, in initialize_databases
odoo_1  |     self.channel_manager.notify(db_name, *job_data)
odoo_1  |   File "/mnt/third-party-addons/queue_job/jobrunner/channels.py", line 1011, in notify
odoo_1  |     assert job.db_name == db_name
odoo_1  | AssertionError
```
Seems the database that the job is expected is not the current one. It is fine but it eats the memory like pancakes.

What do I do wrong ? Would you have advices ?

Thank you,
Jordi

**Comment by sbidoul** [comment]
Could it be you have copied a database and you have the same job uuid in more than one database?
In which case the uuid is not so unique anymore and weird things happen.

**Comment by foutoucour** [comment]
Indeed we do copy the database for lazy reasons :)

Thank you, I can now see how we will fix the fact that our uuid are not so unique.

Cheers
Jordi
