### ISSUE TITLE
[10.0] Pending jobs not starting when there is more than one database

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/queue#170]
I have found that the [call](https://github.com/OCA/queue/blob/10.0/queue_job/jobrunner/runner.py#L396) to `/queue_job/session` returns 404 instead of a session when there is more than one database in the system; even when dbname is specified correctly.

**Comment by flotho** [comment]
Same issue here,

**Comment by mohamedhagag** [comment]
It never executes pending jobs and I'm not sure why.

any update on this ?

is there any way to manually start the job ?


I'm on v12.0 BTW

**Comment by thomaspaulb** [comment]
@mohamedhagag In my case I worked around the problem by remaining with just one database that is matching the "dbfilter".

If you have only one database and still no jobs are started,  make sure that you have:

```
[options]
server_wide_modules = web,connector
[options-connector]
channels = root:4
```

in your odoo.cfg

**Comment by huakkai** [comment]
After the service is started, the new database is not supported. The database list will be loaded when the service is started. In this case, you can try to restart the service or load it dynamically.
