### ISSUE TITLE
13 Job Object Error

### ISSUE THREAD

**Issue by ghost** [OCA/queue#181]
Hi i am getting following error

TypeError: 'Job' object is not callable

here is part of code

`from odoo.addons.queue_job.job import job 
 
 job_descr = _('send invoice #%s') % self.name
 obj.with_delay().send_invoice(self)(description=job_descr)
 
 
 @job(default_channel='root')
    def send_invoice(self, invoice):
        """ Send Invoice to customer. """`

what can be problem ?

**Comment by ghost** [comment]
next stage,
now error is 

ValueError: Wrong value for queue.job.job_function_id: queue.job.function(21, 22)
anyone ? if i not set description and fname its working ?

fname = 'test'
        job_descr = _('file name #%s') % self.name
        obj.with_delay(
            description=job_descr
        ).job_a(file_name=fname)



  @job
    def job_a(self, file_name=None):

        logger.info('fname %s' % file_name)

**Comment by simahawk** [comment]
1. `obj.with_delay().send_invoice(self)(description=job_descr)`

this is wrong: `send_invoice` gives you back a job and you are calling it. `description` should be passed to `with_delay`.

2. seems you have 2 functions w/ the same name.
