### ISSUE TITLE
[RFC] define the job vacuum delay per channel

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/queue#187]
I am facing some issues on a big project where I manage millions of jobs.
By default, we keep them for 30 days.
For some process this delay is too long but for other ones it is ok.

I am currently working on an addon allowing to define the vacuum delay per channel.

If somebody have suggestions or remarks on this idea, feel free to comment.

**Comment by guewen** [comment]
It makes sense, my only remark is, it should be in the base addon ;)
Delay configured on the `queue.job.channel` channel.

**Comment by Cedric-Pigeon** [comment]
@guewen Thanks ! I will do this way.

**Comment by guewen** [comment]
Merged in all branches, so I close this. Thanks!
