### ISSUE TITLE
[RFC] planned exports on base_export_async

### ISSUE THREAD

**Issue by guewen** [OCA/queue#196]
We'll write a new feature based on `base_export_async`, where you can choose a model, an export list, a domain, a list of recipient users and a frequency. A new model will hold this configuration to be able to configure as many planned exports as we want.
A cron will generate a `delay_export` job based on these.

Any comment, ideas, proposals?
Also, should we include it in `base_export_async` or add this in an module depending on it?

cc @apineux @lmignon

**Comment by simahawk** [comment]
You can use ir.export for the conf.

**Comment by guewen** [comment]
It's there https://github.com/OCA/queue/pull/197 :)

**Comment by guewen** [comment]
Merged in 12.0
