### ISSUE TITLE
[Feature] Concurrent job runners

### ISSUE THREAD

**Issue by guewen** [OCA/queue#2]
In a use case with several hosts running Odoo, we might want either to:

* allow several jobrunners to run concurrently on several hosts, which might be hard due to the queues kept in local memory
* elect a master jobrunner allowing to work, the other ones wait and one of them takes over if the master is down

**Comment by lasley** [comment]
IMO the best way to implement this would be a Message Broker, such as [RabbitMQ](https://www.rabbitmq.com/getstarted.html). 

We would just need to advertise to and ingest from a simple Work queue. In the event of the master down, an [Alternate Exchange](https://www.rabbitmq.com/ae.html) would do nicely I think.

**Comment by yucer** [comment]
Odoo optionally uses [gevent](https://github.com/odoo/odoo/blob/10.0/addons/bus/models/bus.py#L179) for the bus. So the dependency is already there.

Maybe [gevent.queue](http://www.gevent.org/gevent.queue.html) can be used with that purpose.

**Comment by thomaspaulb** [comment]
_Elect a master jobrunner allowing to work, the other ones wait and one of them takes over if the master is down_

Could this be done via a database lock? Eg. each Odoo instance regularly tries to grab a database lock by which to become the master job runner; if it succeeds, it becomes, if not, does nothing and tries again after a while.

**Comment by thomaspaulb** [comment]
Something like this:

https://github.com/OCA/OCB/blob/11.0/odoo/addons/base/ir/ir_cron.py#L209

**Comment by nilshamerlinck** [comment]
Hi @thomaspaulb you might want to have a look at https://github.com/OCA/queue/pull/256 :)

**Comment by thomaspaulb** [comment]
@nilshamerlinck I actually just found that one too haha, thanks.
