### ISSUE TITLE
queue_job_batch: permission issues when user is in group queue_job_batch_user

### ISSUE THREAD

**Issue by sbidoul** [OCA/queue#202]
When the user is only in group queue_job_batch_user
- one must use `sudo` to call `enqueue()` on the new batch
- the user cannot mark job batch as read because `set_read()` raises a permission error

What would be the best approach:
- use `sudo` in `set_read()` and `enqueue()`
- add `write` permission on `queue.job.batch` for the `queue_job_batch_user` group (knowing there is a record rule allowing users to view their own batches only

@etobella @lreficent  what do you think?

cc/ @qgroulard

**Comment by LoisRForgeFlow** [comment]
As long as the batch is created with the correct used_id I'm fine with any option, which I think it will be the case if you use the [get_new_batch](https://github.com/OCA/queue/blob/12.0/queue_job_batch/models/queue_job_batch.py#L112) method (btw, it already uses sudo).

Maybe the easiest and the one with less impact is the first one (use sudo in a couple of places more)?

**Comment by etobella** [comment]
Maybe it is cleaner to use second option, I think it is better to use sudo only if necessary.

**Comment by LoisRForgeFlow** [comment]
My only point against is that the user will see the option to edit when in the batch views, but we could change also the view definitions with edit="false". So let's go for the second then

**Comment by LoisRForgeFlow** [comment]
This can be closed.
