### ISSUE TITLE
_compute_job_function Error

### ISSUE THREAD

**Issue by liweijie0812** [OCA/queue#206]
https://github.com/OCA/queue/blob/fe44269c43d4fc41784395bab1962b86b758143b/queue_job/models/queue_job.py#L372
 _find_or_create_channel creates multiple records due to concurrency problems.
https://github.com/OCA/queue/blob/fe44269c43d4fc41784395bab1962b86b758143b/queue_job/models/queue_job.py#L106
Cause "_compute_job_function" execution error.

**Comment by pedrobaeza** [comment]
Unless you specify more the steps to reproduce the problem, this is working correctly in our end.

**Comment by liweijie0812** [comment]
I can't try it out in the new environment. I'll bring up the issue when I'm found.

Sorry to bother you.
