### ISSUE TITLE
Licence understanding

### ISSUE THREAD

**Issue by yelizariev** [OCA/queue#207]
Can the modules, say `queue_job`, be used along with private modules? I consider only cases when the website (odoo) is available publicly on internet (i.e. it's not some deployment available in via local network only). I would like to know under which circumstances a random person has a right to get private code that the hypothetic website uses 

Possible types of usage:

1. private code uses or doesn't use queue_job
2. functionality of the private code is accessible or not accessible by the person (e.g. the functionality can be used only via the backend to which the person doesn't have access)

**Comment by guewen** [comment]
Hi @yelizariev, I missed your question. The addon being LGPL now, yes it can be used alongside or with dependencies from private modules. And there is no network clause in LGPL, users can't ask the private code when they use it through their browser.

Now if you have other addons licensed as AGPL, which include a network clause, it would be different.

**Comment by yelizariev** [comment]
Thank you, that makes things easier
