### ISSUE TITLE
V11 Migration

### ISSUE THREAD

**Issue by gdgellatly** [OCA/queue#22]
Hi,

I have a v11 requirement that needs to happen pretty quickly after release so I've started work on this on master.

You can follow work here, pretty minimal so far, just got it installing.  Note the change to config file needed.

https://github.com/gdgellatly/queue/tree/11.0

**Comment by lepistone** [comment]
Thanks @gdgellatly ! @guewen and I are continuing your work in https://github.com/lepistone/queue/tree/migrate-v11

**Comment by pedrobaeza** [comment]
I have just created the 11.0 branch with the migration script and the tracking issue #29, so you can continue there.
