### ISSUE TITLE
[Question] License queue modules v11, v10 (LGPL, AGPL)

### ISSUE THREAD

**Issue by bobslee** [OCA/queue#225]
Regarding the license change to **LGPL-3** in the (queue) modules **v13** and **v12**.

I noticed the license in **v11** and **v10** is still **AGPL-3**.
Would it be possible to apply **LGPL-3** please?

**Comment by guewen** [comment]
Hi, as for OCA/connector, considering we did the change on upper versions, I would approve a pull request switching the license to LGPL-3.

**Comment by guewen** [comment]
I close this as the license has been changed in 10.0 and 11.0. Thanks!

**Comment by bobslee** [comment]
Thanks @guewen !
