### ISSUE TITLE
Job state started and not done

### ISSUE THREAD

**Issue by heshammostafa07** [OCA/queue#226]
I am trying to install odoo modules as a job using queue_job module. I am using below code

@job
def install_modules(self, dbname):
    self.ensure_one()
    db = sql_db.db_connect(dbname)
    with api.Environment.manage(), db.cursor() as cr:
        env = api.Environment(cr, SUPERUSER_ID, {}) 
        module_ids = env['ir.module.module'].search([('name', '=', 'purchse')])
        module_ids.button_immediate_install()

Job executed but the job finally not converted to done state it is still started

**Comment by guewen** [comment]
Hi,

IIRC, the installation of modules do some trickery to the registry and environment, I think it totally resets all the running environments, including the one used by the job. It's worth checking exactly what it's doing under the hood, but that's maybe not something which can be supported?

**Comment by guewen** [comment]
Same as https://github.com/OCA/queue/pull/215#issuecomment-635790754

**Comment by guewen** [comment]
Closing as duplicate.
