### ISSUE TITLE
Create/update trigger on module installation

### ISSUE THREAD

**Issue by sbidoul** [OCA/queue#245]
The database [trigger](yhttps://github.com/OCA/queue/blob/a07d3735c74166b6b1e0a756107fc012cb1bc4a5/queue_job/jobrunner/runner.py#L518) that emits the NOTIFY events is created/updated [during job runner startup](https://github.com/OCA/queue/blob/a07d3735c74166b6b1e0a756107fc012cb1bc4a5/queue_job/jobrunner/runner.py#L518).

When the runner crashes and restart (e.g. when the database connection is lost temporarily) it attempts to drop/recreate the trigger. This requires an exclusive lock on the queue_job table and causes issues when this happens while other transactions are busy creating many jobs.

A solution is to move the trigger creation to module installation time in a post init hook.

**Comment by guewen** [comment]
Fixed by https://github.com/OCA/queue/pull/247, https://github.com/OCA/queue/pull/248 in 12.0/13.0
