### ISSUE TITLE
simplejson over json

### ISSUE THREAD

**Issue by iledarn** [OCA/queue#251]
This is not an issue, as it is a rare case and can be fixed quickly - just my thoughts and maybe someone else encounter the same problem.

I'm trying to create a job with data containing Decimal object (from decimal python lib) and getting such error
`Object of type 'Decimal' is not JSON serializable`. The `simplejson` can handle such types of objects and much more. So, maybe to use JSONEncoder/JSONDecoder from simplejson? I've fixed my problem with `import simplejson as json`

I googled about it and have got the following
`json is simplejson , added to the stdlib. But since json was added in 2.6, simplejson has the advantage of working on more Python versions (2.4+). simplejson is also updated more frequently than Python, so if you need (or want) the latest version, it's best to use simplejson itself, if possible.`

https://artem.krylysov.com/blog/2015/09/29/benchmark-python-json-libraries/

**Comment by iledarn** [comment]
rare case and can be fixed quickly on site

**Comment by guewen** [comment]
If needed, `Decimal` could be added to our custom encoder/decoder: https://github.com/OCA/queue/blob/3b49e066c55a2d184ba1b358fde9dc7d9123843e/queue_job/fields.py#L57-L99

**Comment by iledarn** [comment]
thx, I thought about it either. I did see how it is implemented in simplejson - there were many lines of code and I decided just to `import simplejson as json` in the head of `queue/queue_job/fields.py` for now
