### ISSUE TITLE
[Feature] simplification of jobs form view

### ISSUE THREAD

**Issue by guewen** [OCA/queue#28]
The form view is repellent for less technical users, we could improve that with some improvements:

- Customize the view for normal users and technical users, we have yet to decide if it's based on groups or `?debug`
- on errors, record the error message (without traceback) in the result field
- hide the following fields for non-technical users:
  - Task
  - Job function
  - Channel
  - Exception Information
  - Company depending of the multi-company group
  - Enqueue time

- Add the model in filters and group bys, and the model with the "human name"

Besides this purely visual aspect, we should encourage developers to have their jobs returning values so they get a result which could give more information about what happened (such as 'Stock has been exported with a quantity of xx....'). We have to check if this result is / can be properly translated in the language of the user who created the job.

A bit unrelated, but we should see if we can't inhibit the "Queue Job created" notification.

**Comment by lasley** [comment]
I couldn't agree more @guewen. My thoughts regarding whether sec group or `?debug` is that it should be security group.

Rationale behind this is that I consider `?debug` to be things that an implementor is going to use - either during initial setup or while changing the instance somehow. These fields are more of a day-to-day thing for the users that understand them though (at least IMO).

**Comment by lasley** [comment]
> A bit unrelated, but we should see if we can't inhibit the "Queue Job created" notification.

Totally. All of my implementations actually have human users blocked from the queue permissions so they don't get spammed with the job logs via email. I've been meaning to submit a PR to make this more elegant for a long time.

**Comment by guewen** [comment]
> Rationale behind this is that I consider ?debug to be things that an implementor is going to use - either during initial setup or while changing the instance somehow. These fields are more of a day-to-day thing for the users that understand them though (at least IMO).

It makes sense, I agree with your point.

**Comment by lasley** [comment]
I'm thinking more about this inhibiting of the notifications. Would something simple like an additional security group for notifications be enough? I've found that basically none of my users care about the queue notifications, but they do want to manage the queue from UI.
