### ISSUE TITLE
access job queue variables from within delayed function

### ISSUE THREAD

**Issue by t-900-a** [OCA/queue#298]
https://github.com/OCA/queue/tree/13.0/queue_job

I need to do some final processing, if a job is on it's last retry.

In order to do so I need to access the following variables:
Retries: Ability to retry jobs by raising a type of exception
Retry Pattern: the 3 first tries, retry after 10 seconds, the 5 next tries, retry after 1 minutes, .

Is this possible from within a function?

The queue is defined here: https://github.com/t-900-a/moneroodoo/blob/dev/monero-rpc-odoo/data/queue.xml

The function is defined here: https://github.com/t-900-a/moneroodoo/blob/f0e3feff92e2d94bec386530c353a5eca7941deb/monero-rpc-odoo/models/sales_order.py#L24

**Comment by guewen** [comment]
You have the job's uuid in the context key `job_uuid`, from there, you can find the job record and read its data.

**Comment by t-900-a** [comment]
Do I have to pass the context key to the function?
Or is the key added to "self"?

Thank you for your help

**Comment by guewen** [comment]
Within the execution of a job, the key is already there in `self.env.context`
