### ISSUE TITLE
Finish project setup (travis, etc)

### ISSUE THREAD

**Issue by sbidoul** [OCA/queue#3]
- [x] CLA bot
- [x] IRC bot
- [x] Twitter
- [x] Travis was ok
- [x] Coveralls
- [x] added to OCA web site page: https://odoo-community.org/project/connector-maintainers-34
- [x] runbot
- [x] update OCA/maintainer-tools https://github.com/OCA/maintainer-tools/commit/59d57c9e7b8299982ab3fb7e4bc88a72c95c6ffe
- [x] repo labels

**Comment by sbidoul** [comment]
@guewen all done. Let me know of any issue.

**Comment by guewen** [comment]
Thanks!
