### ISSUE TITLE
Started job continues execution on requeue

### ISSUE THREAD

**Issue by guewen** [OCA/queue#306]
When a running job is requeued, the worker that started the execution continues to run, the job is set back to pending and start again. Then, the 2 workers have to update the state of the job to `done` and one has a concurrency error.

In the "Jobs Garbage Collector" cron, there is the possibility to define a delay after which started jobs are requeued automatically:
https://github.com/OCA/queue/blob/56b56f4e8e830e1bd63ea96313f2e4035584f382/queue_job/models/queue_job.py#L306-L312

This is very dangerous, as the job will be requeued in lead to this issue.

**Comment by guewen** [comment]
I tried a quick experiment with:

```
    def requeue(self):
        for record in self.filtered(lambda record: record.state == "started"):
            os.kill(self.worker_pid, 1)
        self._change_job_state(PENDING)
        return True
```

Which works smoothly as long as...

* you use multiprocess and not multithread
* all the odoo processes are on the same node: if the worker that requeues is not on the same host as the worker executing the job, you kill the wrong pid
* after the restart of a host, the pid of a started but not running anymore job (force-killed) could be assigned to a different process now

 The first one could be acceptable, the 2 last ones, big nope

**Comment by thomaspaulb** [comment]
_When a running job is requeued, the worker that started the execution continues to run, the job is set back to pending and start again._

Is that still true after https://github.com/OCA/queue/pull/131/files ? The job is set back to pending yes, but it won't start again as long as the old one is still running and thus holding the lock.
