### ISSUE TITLE
Queue execute tasks on different channels

### ISSUE THREAD

**Issue by claudioamaro** [OCA/queue#307]
Hi, I have a database with several channels on different hosts, where any task in the queue is handled by any available channel, which in my opinion is good when I do with_delay () without specifying the channel, but I also have a task that I would like to be handled by a single channel, with_delay (channel = 'root.name_channel'), even if other channels are available and the specified channel is not, they should ignore this task and can only be handled by the specified channel.

**Comment by guewen** [comment]
Hi, if you have no capacity in `root.name_channel` because you configured X slots and X jobs in this channel are executing, no more job with channel `root.name_channel` will be executed. Did you properly configure a capacity for the channel in the variable `ODOO_QUEUE_JOB_CHANNELS` (eg. `ODOO_QUEUE_JOB_CHANNELS=root:6,root.name_channel:1`)?

>  I have a database with several channels on different hosts

What do you mean? How do you do that? This is not something normally supported by `queue_job` :)

**Comment by aliencrash** [comment]
What @claudioamaro  is trying to explain is that we have different odoo instances connected to the same odoo database, but each of them are configured to process different queue channels. 

The thing is that we would like to make specific tasks to be executed by specific odoo instance configured with an specific channel. What we notice now is that even if we configure the channel in on instance, we see that other tasks that are not associated to that instance and channel are also executed. 

So the question is if there is a way to instances ignore task that are not from their channel.

**Comment by guewen** [comment]
I see, the thing is channels are always joined in their parent channel:

https://github.com/OCA/queue/blob/563db616ff33496b75e82b98f9734c8c66637ce4/queue_job/jobrunner/channels.py#L372-L381

I see what you'd like to do. Currently, all the channels must have a parent and eventually bring to `root`. The work here would be to be able to have several hierarchies of channels and be able to start the jobrunner on one or another (one would work on `root` and its children, another would work on `foo` and its children...).

AFAIK this is not possible now.

**Comment by aliencrash** [comment]
> I see, the thing is channels are always joined in their parent channel:
> 
> https://github.com/OCA/queue/blob/563db616ff33496b75e82b98f9734c8c66637ce4/queue_job/jobrunner/channels.py#L372-L381
> 
> I see what you'd like to do. Currently, all the channels must have a parent and eventually bring to `root`. The work here would be to be able to have several hierarchies of channels and be able to start the jobrunner on one or another (one would work on `root` and its children, another would work on `foo` and its children...).
> 
> AFAIK this is not possible now.

Ok. Would it be too much to develop it?

**Comment by guewen** [comment]
Maybe not... what you can try hacking is:

* modify https://github.com/OCA/queue/blob/563db616ff33496b75e82b98f9734c8c66637ce4/queue_job/jobrunner/channels.py#L803 not to be hardcoded to `root` (at first you could hardcode 2 different values in your 2 services to try, later we could initialize it from the `ODOO_QUEUE_JOB_CHANNELS` config) 
* remove the required on channel's parent_id: https://github.com/OCA/queue/blob/563db616ff33496b75e82b98f9734c8c66637ce4/queue_job/views/queue_job_views.xml#L251
* configure 2 trees of channels according to your changes in ChannelManager

Then, we have places where the default channel is `root` (https://github.com/OCA/queue/blob/563db616ff33496b75e82b98f9734c8c66637ce4/queue_job/models/queue_job.py#L593), I suppose this could be kept and documented that you must have at least one jobrunner handling the `root` channel.

**Comment by aliencrash** [comment]
Ok. Thanks. We will look into it.
