### ISSUE TITLE
[14.0] queue_job: Odoo app store publication

### ISSUE THREAD

**Issue by trojikman** [OCA/queue#318]
Will it available in the app store? We have some modules that depend on it to be published. 
It would be great to have queue_job there.
Link to v13: https://apps.odoo.com/apps/modules/13.0/queue_job/

@pedrobaeza, maybe you can help?

**Comment by pedrobaeza** [comment]
I'm not managing that. Maybe @dreispt can do it?

**Comment by ventor-dev** [comment]
@dreispt are you responsible to publish Odoo 14 on App store? I can do it myself from my account, but I prefer that it will be published by single person

**Comment by simahawk** [comment]
https://apps.odoo.com/apps/modules/14.0/queue_job/

**Comment by trojikman** [comment]
Thank you very much!
