### ISSUE TITLE
[13.0] Missing post-migration script?

### ISSUE THREAD

**Issue by BT-rmartin** [OCA/queue#321]
Hi, 
When migrating a db with the module queue_job installed from 12.0 to 13.0 this [post_init_hook](https://github.com/OCA/queue/blob/13.0/queue_job/hooks/post_init_hook.py#L14) is not executed, as the modules was already installed and keeps like that.  
Shouldn't there be a post-migration script also for executing that SQL code?
Otherwise it's missing in the new db unless you uninstall and install the module. 
Or this there any other way to get it that I missed?
Thanks in advance for your help
@guewen

**Comment by guewen** [comment]
Hi, can you have a look at #304 and give a feedback if it solves the issue?
