### ISSUE TITLE
License Clarification Required v13 onwards 

### ISSUE THREAD

**Issue by chrisv1351** [OCA/queue#331]
queue_job is LGPL-3 where in other modules like queue_job_cron, base_import_async, base_export_async are still AGPL-3. Is it intentionally kept as AGPL-3 or Forgot to change ? 

I have checked in v13 repo and __manifest__.py file for each of the above mentioned modules.

**Comment by pedrobaeza** [comment]
Why do you want such secondary modules to be `LGPL`? The main one has been done LGPL, as is a base module, and for being tolerant with private extensions, but the other are still AGPL on purpose, as they are not intended to serve as base for other things, and if so, they should be AGPL and released as well. If you want an specific one of them to be changed its license, you will have to ask their authors about that.

**Comment by chrisv1351** [comment]
from my experience, it is better to have a harmonized licenses at branch or at repo level in order to avoid any conflicts or confusion to developer.

**Comment by pedrobaeza** [comment]
That's not needed and there's no conflict. Each developer chooses the license they want for their modules while being compatible, and this scheme is compatible.

Closing as this is not an issue, but a question, and it has been solved.
