### ISSUE TITLE
We suggest a new module: queue_job_cleanup

### ISSUE THREAD

**Issue by agent-z28** [OCA/queue#337]
As we have 100.000+ QueueJobs per day with a lot of json data, the database size increases quickly.
We plan to realize a module to automatically unlink queue.jobs after a  configureable hold-back time.
@guewen what you say?

**Comment by guewen** [comment]
Hi @agenterp, there is such a scheduled action already. "autovacuum queue jobs" IIRC. The default configuration is 30 days. The number of days can be configured on the job channels (but maybe not on all versions, it could be in the scheduled action directly).

**Comment by agent-z28** [comment]
@guewen indeed :D thank you very much for this hint
