### ISSUE TITLE
Kill job

### ISSUE THREAD

**Issue by rquevedo** [OCA/queue#339]
Hi folks,
How can i terminate a queue job before ends. Some like kill process.
Thanks in advance.

**Comment by PieterPaulussen** [comment]
Hi! @rquevedo Please take a look at this PR for some idea: https://github.com/OCA/queue/pull/334

**Comment by StefanRijnhart** [comment]
Good timing ;-) Closing as the related PR, which is now merged, indeed allows to kill the database transaction of the running job, which will kill the job at the next database query. So effectively it can be used to kill most types of jobs.
