### ISSUE TITLE
RFC: mark jobs as cancelled

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/queue#342]
In Odoo 8.0, we occassionaly use the option to set jobs to inactive + failed to mark jobs as (temporarily) cancelled. We do this to manage unexpected concurrency problems or performance problems. We reactivate the jobs and reset to pending after office hours or when an underlying condition is fixed.

I've only just noticed that in later versions, this is no longer possible because the `active` flag was removed here https://github.com/OCA/connector/pull/198 because it was obsolete for its original purpose. I would either like to reintroduce the flag, or to introduce a dedicated `cancelled` state.

cc: @PieterPaulussen

**Comment by PieterPaulussen** [comment]
@StefanRijnhart Don't you agree that we misused the failed-active combination in our setup? I would add a new `cancelled` state rather than re-add the original columns.

**Comment by StefanRijnhart** [comment]
Well, I am neutral to the solution, but I did mention having a distinct cancelled state as one of the options.

**Comment by etobella** [comment]
Well, in this case, I would use something like `draft` or `blocked`, as the job is not `cancelled` it is just waiting for some conditions

**Comment by StefanRijnhart** [comment]
That's our use case, but if the job is never restarted it is actually `cancelled`. Currently we set jobs to done manually for that, but that is a bit misleading as well.

**Comment by StefanRijnhart** [comment]
So I imagine
* a list action 'Cancel jobs', applied on pending/failed jobs from the selection
* the list action 'Requeue jobs' to work on cancelled jobs as well as on jobs in other states
* Button 'Set Done' on failed jobs replaced by 'Cancel job'
* Cancelled jobs vacuumed just like Done jobs are.

**Comment by guewen** [comment]
Hi, 

IMO `active` is just too risky / confusing as jobs are out of visibility (BTW I'm not very happy with the default security rules on `company_id` for the same reason). I think jobs should never be hidden by default.

As for a cancelled state, the discussion popped in several times and it was unclear if it was really needed vs set to done and the simple option won.
But I reckon the description of your requirements makes sense, and could be a nice addition.

**Comment by hbrunn** [comment]
so I'll go ahead and implement Stefan's bulletpoints

**Comment by StefanRijnhart** [comment]
@hbrunn great! As always, it was a quick write-up that may not be entirely correct or exhaustive. Let me know if you have any doubts or new insights.

**Comment by hbrunn** [comment]
https://github.com/OCA/queue/pull/347
