### ISSUE TITLE
Can't start queue_job On Ubuntu 16.04, Odoo v13 Comm

### ISSUE THREAD

**Issue by dinhngcong** [OCA/queue#354]
I'm try config Queue job in server production
![image](https://user-images.githubusercontent.com/80304736/120658820-f8f41a00-c4af-11eb-981a-287108e1b1f5.png)
but when I start service Odoo, queue_job not working.
![image](https://user-images.githubusercontent.com/80304736/120659092-38bb0180-c4b0-11eb-80f9-8aef3979fca9.png)

Please helpme resolve this issue.

Manythanks.

**Comment by acsonefho** [comment]
@dinhngcong can you ensure this hook is applied please?
https://github.com/OCA/queue/blame/13.0/queue_job/hooks/post_init_hook.py
If not, just apply it manually.
Then restart Odoo

**Comment by dinhngcong** [comment]
> @dinhngcong can you ensure this hook is applied please?
> https://github.com/OCA/queue/blame/13.0/queue_job/hooks/post_init_hook.py
> If not, just apply it manually.
> Then restart Odoo

Thank you a lot
