### ISSUE TITLE
[12.0] Corrupted xlsx attached to failed job

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/queue#360]
STEPS TO REPRODUCE

In any model > import a file > flag "import in the background"
Go to queue > jobs > find out one job has failed for some error

In record attachment, there is an xlsx with the batch of rows that failed - this is useful as I can download the xlsx, correct the issue, and upload again

![image](https://user-images.githubusercontent.com/55489873/125607525-e009194e-a2e3-4845-942b-2e23a4472496.png)

When I try to open the file though, I get excel error "Excel cannot open the file ‘(filename)’.xlsx because the file format for the file extension is not valid. Make sure file is not corrupted and extension is correct"

Tested on Excel 365, anyone else experiencing this?

**Comment by guewen** [comment]
@francesco-ooops I think the xlsx is converted to csv when it is split, and the problem would be that it keeps the .xlsx extension.
Could you try to rename the file to .csv / open it with a text editor?

**Comment by francesco-ooops** [comment]
> @francesco-ooops I think the xlsx is converted to csv when it is split, and the problem would be that it keeps the .xlsx extension.
> Could you try to rename the file to .csv / open it with a text editor?

Hi, yes I can open the file by renaming the extension to .csv, then make the necessary edit and upload again, but if it's not too much work it would be great if the split file got the correct csv extension

thanks!
