### ISSUE TITLE
[12.0] queue_job, missing _compute_job_function

### ISSUE THREAD

**Issue by GSLabIt** [OCA/queue#368]
Hi @guewen,

https://github.com/OCA/queue/blob/d76f43527e14500a9c777890ed9bba4390688f7e/queue_job/models/queue_job.py#L105-L107

seems `_compute_job_function` is missing on `queue_job`, should it be added or compute needs to be removed?

**Comment by guewen** [comment]
Hi, thanks, see #357, waiting for reviews 🙂

**Comment by GSLabIt** [comment]
wooopssss, sorry ..

**Comment by GSLabIt** [comment]
@guewen any eta to merge it? actually it is not possible to install `queue_job`, it's a blocking issue.
