### ISSUE TITLE
[14.0] exception while odoo.addons.queue_job.jobrunner.runner: initializing database connections

### ISSUE THREAD

**Issue by coolspawn** [OCA/queue#370]
Exception in run(). Fall into  "exception: sleeping %ds and retrying", ERROR_RECOVERY_DELAY
because no dbname found (in sentry dbname = ?)
![Screenshot from 2021-08-18 09-24-37](https://user-images.githubusercontent.com/49014515/131545446-7310651f-5ab8-498e-a5d9-80c3055983c8.png)

In local and testing environments works fine

**Comment by nilshamerlinck** [comment]
Hi @coolspawn the error message "cannot execute LISTEN during recovery" seems to indicate that the pg server was not fully ready yet, possibly recovering after a crash? Did it manage to initialize after some attempts, once the pg server was ready?

**Comment by coolspawn** [comment]
My fault, we have 3 instatnces, and master swithched to another node, this is why queue_job crashed
