### ISSUE TITLE
RFC: Jobrunner channels as cron jobs?

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/queue#371]
The decision to write the jobrunner was made [very early on](https://odoo-connector.com/8.0/api/api_runner.html). In my understanding, it was designed to allow fast parallel execution of background jobs in multiple channels, also allowing a hierarchy of channels.

However, I'm asking myself why not offer users the alternative to use `ir.cron` to run jobs. That would look as follows:

- Each channel has a corresponding `ir.cron` record, disabled by default
- These crons trigger periodically eg. every 1 minute or 5 minutes (configurable)
- When triggered, the cron start a loop to processing jobs assigned to the channel, just like the jobrunner does. The loop can be configured to run a maximum of eg. 100 times or 1000 times (configurable) before it stops and waits to be triggered again. Of course, a database commit would run after each iteration.

What would be the benefits or problems with such an approach?

Benefits I can think of:

- It would play well with [odoo.sh](https://github.com/OCA/queue/pull/256)
- It's easier to configure eg. no `server_wide_modules` or special Odoo settings
- It's less complex / easier to understand / debug
- It's straightforward to enable or disable a channel
- Channels could be created and removed dynamically

Downsides:

- There will be periods of 'pause' when no jobs are run - between the end and the next trigger of a cron run
- Hierarchy of channels / channel capacity could be more difficult to implement
- `max_cron_threads` would have to be high enough, warn user if he exhausts them
- ... probably some I havent thought of

**Comment by yelizariev** [comment]
> There will be periods of 'pause' when no jobs are run - between the end and the next trigger of a cron run

It's not the case since Odoo 15: https://github.com/odoo/odoo/commit/4b28f1162a85d03f9dbe0338b06758ad151ea6a8

**Comment by simahawk** [comment]
@guewen shall we close this?

**Comment by ivantodorovich** [comment]
See: 
- https://github.com/OCA/queue/pull/415
