### ISSUE TITLE
[13][14][15]PGBouncer problem...

### ISSUE THREAD

**Issue by esakarya** [OCA/queue#376]
queue jobs wont start with pgbouncer.

**Comment by eLBati** [comment]
We probably need something similar to https://github.com/OCA/server-tools/tree/12.0/bus_alt_connection

**Comment by eLBati** [comment]
Actually, this is already implemented in `queue_job` with `ODOO_QUEUE_JOB_JOBRUNNER_DB_HOST` and `ODOO_QUEUE_JOB_JOBRUNNER_DB_PORT`
