### ISSUE TITLE
11.0 raise from python3 expr in

### ISSUE THREAD

**Issue by Karsten-77** [OCA/queue#38]
Hello,

that line seems to be wrong, my IDE calls it incompatible with 2.7.12:
https://github.com/OCA/queue/blob/11.0/queue_job/job.py#L380

Recommend to use package future and change to:
raise_from(new_exc, err)

regards,
Karsten

**Comment by bealdav** [comment]
Hey  @Karsten-77 it seems only python 3 will be completely supported

**Comment by lmignon** [comment]
@bealdav You are right as for Odoo 11,  queue job only supports python3.
