### ISSUE TITLE
How can we stop Job Queue from running (temporarily during update modules)

### ISSUE THREAD

**Issue by kittiu** [OCA/queue#385]
Hi,

I want to find the right way to "Pause" or "Stop" every job from running. Currently, we have an update process that will take some time to run, and it always conflict with the running job.

Thanks!

**Comment by ventor-dev** [comment]
@kittiu you need to run upgrade process from command line. Also specify --workers=0 
As result Odoo will not run any cron threads or runner threads

Below command we run to upgrade modules and it works good. Moreover it is easy to include it into auto-deploy scripts

odoo-bin -c <odoo-conf> -u <mondeules_to_update> -d <database_name> --stop-after-init --no-http

**Comment by kittiu** [comment]
Great 👍
Thanks so much.
cc @Saran440

**Comment by Saran440** [comment]
@ventor-dev okay it's work! Thank you very much :)
