### ISSUE TITLE
[10.0]Excpetion issue

### ISSUE THREAD

**Issue by flotho** [OCA/queue#39]
Hi,
I'm trying to raise an exception and I have this message :
```
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
```
I tried many ways, what is the old-style classes way ?

**Comment by guewen** [comment]
Hi, could you give more information about what you are trying to do? Show some code? A traceback?

**Comment by flotho** [comment]
Hi,

Forget, this one was a bad syntax from my side.
regards
