### ISSUE TITLE
[FEATURE] jobify ir_cron

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/queue#40]
Hello,

The most painpoint with ir_cron is that you are not able to have a feedback in case of failure except by reading server logs.
My intend is to create a new module adding a flag "Manage by job" on a cron.
If this flag is checked, the user can specify a channel to use, default will be root, and each execution will be done through a queue job.
By this way users will be able to track faillings cron and eventually relaunch it.

Any feedback on that ?

**Comment by Cedric-Pigeon** [comment]
@guewen @lmignon

**Comment by sbidoul** [comment]
I'd call the flag "Run as Queue Job". Otherwise :+1: great idea.

`queue_job_cron` as module name?

**Comment by JordiBForgeFlow** [comment]
That would be great!! :+1:

**Comment by Cedric-Pigeon** [comment]
queue_job_cron seems good to me.

**Comment by lmignon** [comment]
:+1: great Idea!

**Comment by simahawk** [comment]
:+1:

**Comment by guewen** [comment]
I like this idea *a lot*.

A random thought: it could maybe allow several types of time intervals : N minutes after the end of the last execution, N minutes after the last execution except if still running, N minutes after the last execution no matter what and allowing overlap (need the method to be compatible).

**Comment by JordiBForgeFlow** [comment]
Would be also very good to establish dependencies.between jobs to prevent
potentially conflicting different jobs to overlap. See
https://github.com/OCA/server-tools/pull/999

**Comment by sbidoul** [comment]
> dependencies.between jobs

@jbeficent there is a concept of sequential channels in the queue job runner that guarantees job execution order. That should be sufficient for most purposes.

**Comment by sbidoul** [comment]
@guewen we already have is the throttling option in channels configuration.

**Comment by JordiBForgeFlow** [comment]
Oh, so even whe jobs are assigned to different ir.cron, if they belong to
the same channel they would be executed sequentially, right?

I can think, though, of jobs with different execution frequencies that you
would not want to conflict. But perhaps this is too specific to a problem
we face in DDMRP where we need.to update different attributes of the buffer
in separate crons (Average Daily Usage is computed every 8 hrs and DDMRP
alerts every 2 hrs).

**Comment by sbidoul** [comment]
@jbeficent actually you can simply put all these jobs in a channel with capacity 1 (not necessarily sequential) to be sure they will not run concurrently.

**Comment by JordiBForgeFlow** [comment]
Good! Lookong forward to using it!

**Comment by elicoidal** [comment]
:+1:
