### ISSUE TITLE
Create, Enqueue and Started Datetime Mismatch 

### ISSUE THREAD

**Issue by fredwilliam** [OCA/queue#411]
I created task and here are the datetime recorded

Created Date | 07/03/2022 02:29:11
Enqueue Time | 06/03/2022 23:29:11
Start Date | 07/03/2022 02:29:11

This is the correct time of as of creation 06/03/2022 23:29:11

Created time seems to be pushed +3hrs ahead this makes execution not starting right away.

My Guess this is timezone issue, is it not supposed to store datetime in utc? so that it can be correctly translated to proper timezone accordingly? 

## Module
queue_job

## Describe the bug
Created time seems to be pushed +3hrs ahead this makes execution not starting right away.

## To Reproduce
**Affected versions**:
12.0

1. set your timezone to Africa/Dar es salaam
2. create task

**Expected behavior**
Expected to have created time to be current time of creation not +3hrs 

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by m3asmi** [comment]
Hello @fredwilliam 
I suggest you tu add this line in your systemd service:

`ExecStartPre=/usr/bin/sudo -u postgres /usr/bin/psql DataBaseName -c "update queue_job set state='pending' where state in ('started', 'enqueued');"`
