### ISSUE TITLE
[RFC] base_import_async: validation through job queue

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/queue#418]
Hi, in base_import_async "known issues/roadmap" section it says: "Validation cannot be run in the background."

We would like to develop this feature to validate data without the actual import through job queue for version 14. 

Since you have extensive knowledge of this repo, could you advise regarding foreseeable roadblocks to implementation or things to keep in mind? 

Tagging @guewen @sbidoul and @simahawk as recent contributors to this repo. 

Thanks!

**Comment by sbidoul** [comment]
@francesco-ooops The main question to resolve is how to report the asynchronous validation results to the user.

**Comment by francesco-ooops** [comment]
Thanks a lot @sbidoul for your reply. 

I'm not sure if this is what you were referring to, but when an async import job is failing, the single job contains the log with the import errors causing it to fail. I thought that could be the same place to report validation issues.

I am aware that the "readability" of the error log for common user is far from optimal, while it's much better on "standard" odoo import/validation; the biggest issue being that the csv line generating the error is not always specified.

**Comment by sbidoul** [comment]
Sounds reasonable.
