### ISSUE TITLE
[11.0] Serialized field

### ISSUE THREAD

**Issue by dcorio** [OCA/queue#42]
I get this error while installing queue_job on a fresh 11.0:

`AttributeError: module 'odoo.fields' has no attribute 'Serialized'`

**Comment by simahawk** [comment]
@dcorio I told myself this 2 days ago: RTFM :stuck_out_tongue_closed_eyes: 

![image](https://user-images.githubusercontent.com/347149/34100928-57fd1d5e-e3e4-11e7-9612-41dd7ef6f8d8.png)

not very prominent but is there... you should load it before queue_job ;)

**Comment by lukebranch** [comment]
Is there any particular version of requests that is required?

I'm still getting this error with the requests library install in Ubuntu 16.04, Odoo 11.0 hosted in Google Compute.
 
I've tried: 
pip3 install requests
pip install requests
apt-get install python-requests

and while these satisfy the Odoo requirements.txt dependency, this error message persists.

I'm using the connector version in this PR:

https://github.com/guewen/connector/tree/migrate-v11-connector

as well as OCA/Queue 11.0 branch here:
https://github.com/oca/queue

**Comment by guewen** [comment]
@lukebranch what error exactly do you get? The error in the thread is not about requests but about `--load` option which must include `base_sparse_field`.

For the request version, I'd say any version above 2.0.0, I'm not aware of any issue so far regarding requests' version.

**Comment by lukebranch** [comment]
@guewen ,

Thanks for the help.

Here's the traceback i'm getting:
https://gist.github.com/lukebranch/c87b02b6b478cd6efe81369692499370

Here's my odoo-server.conf file's load parameter settings:
load = "web,web_kanban_gauge,base_sparse_field,queue_job"

I've got the latest version of request from pip (2.17 at the time of writing I believe).
 
As far as I understand it, I don't need to install base_sparse_field in a database, I can just load it through the configuration parameters.

**Comment by guewen** [comment]
@lukebranch okay, this is unrelated to `requests` then.
You got tricked by the fact that the `--load` CLI option is called `server_wide_modules` in the configuration file. Your odoo-server.conf should contain:

server_wide_modules = web,web_kanban_gauge,base_sparse_field,queue_job

**Comment by lukebranch** [comment]
@guewen ,

Thanks again for the advice. I honestly have no idea where I got the notion that the server_wide_modules parameter was retired in 11.0 in favour of load.
