### ISSUE TITLE
[Question] Channels / Channel capacity vs. Odoo workers

### ISSUE THREAD

**Issue by fortee** [OCA/queue#431]
First of all the `queue_job` is fantastic, hats off, and thank you for all the work you have put into it!

I would like to ask for some help to better understand the relationship between the defined channels and channel capacity and default Odoo workers.
I'm planning to start using the `queue_job` with the following configuration:

```
[queue_job]
channels = root:6,A:2,B:2,C:2:throttle=1
```

Until now (without the `queue_job` being used) my Odoo servers worker setting was 6.

I would like to know:
- If the `queue_job` job runners will "eat up" normal Odoo workes or it spawns their own separate workers.
- How to calculate the amount of extra Odoo workers I need if those are used by the `queue_job` module

**Comment by sbidoul** [comment]
> If the queue_job job runners will "eat up" normal Odoo workes or it spawns their own separate workers.

Queue job will use regular workers. It will *not* spawn its own.

> How to calculate the amount of extra Odoo workers I need if those are used by the queue_job module

You need one worker per root channel (6 in your case), plus as much as you need for regular interactive users.

**Comment by fortee** [comment]
Thank you for the answer!
