### ISSUE TITLE
[QUESTION][15.0] How to bring queue_job up to par with [14.0]?

### ISSUE THREAD

**Issue by Rad0van** [OCA/queue#435]
I would like to bring `queue_job` up to par with version 14.0 The thing is I do not know how. Let me explain the situation:

- On November 1, 2021 the module was migrated into 15.0 from 14.0 by #384 
- Since that the 14.0 branch has had many PRs merged with the #428 just 22 days ago
- However the 15.0 branch didn't have any merged PRs in that period but 22 days ago received #429 that is identical to the above in 14.0

Now if I want to bring the 15.0 branch up to par wiht 14.0 what should be the correct way of doing it? Should I cherry-pick the interrim PRs? Or should I somehow discard the recent one and get to a point where the branches were identical? Any help is highly welcome. @guewen @pedrobaeza @sbidoul @simahawk @hbrunn

**Comment by hbrunn** [comment]
cherry-pick everything that makes sense in v15, migrate that

**Comment by pedrobaeza** [comment]
Using https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch should work as well for rescuing the different commits. Or use this tool: https://github.com/OCA/maintainer-tools/pull/504

**Comment by Rad0van** [comment]
> Using https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch should work as well for rescuing the different commits. Or use this tool: [OCA/maintainer-tools#504](https://github.com/OCA/maintainer-tools/pull/504)

I am aware of that migration procedure and actively using it for a long time. However as I described in my initial post: the module has already been migrated into 15.0 in November. From that point none but the last PR applied to 14.0 has been applied to it. So I guess cherry-picking as Holger suggests. Or can the `oca-port` start in the middle of the process on already migrated module?

**Comment by pedrobaeza** [comment]
As said, the procedure serves also for bringing up the difference. And `oca-port` serves as well.

**Comment by Rad0van** [comment]
> As said, the procedure serves also for bringing up the difference. And `oca-port` serves as well.

That's great! Will try that out. Thank you.
