### ISSUE TITLE
request for information: how to sequence several jobs in a channed

### ISSUE THREAD

**Issue by ccandito** [OCA/queue#436]
Dear All,
thanks in advance for your support.
I've allocated three scheduled actions to the same channel. What I need is to sequence them, that means the first should start at 12:AM, the second should start after the first is finished and so on.
how is it possible to achieve it?
Regards
Claudio

**Comment by sbidoul** [comment]
@ccandito you need to configure the channel with capacity 1 and declare it to be sequential.

For instance: `root:4,root.myseqchan:1:sequential`

**Comment by ccandito** [comment]
thanks
