### ISSUE TITLE
setting capacity channels in the Odoo configuration file

### ISSUE THREAD

**Issue by ccandito** [OCA/queue#437]
Dear All,
I've set up the configuration file in the following way:
channels = root:4,root.xxx:1,root.yyy:3
server_wide_moduled = web,queue_job

in the log the system shows only one channel configured: root(C:1, Q:0, R:0, F:0)

where was I wrong?

thanks in advance
Claudio

**Comment by sbidoul** [comment]
This must go in a separate queue_job section:

```
[queue_job]
channels = root:4,root.xxx:1,root.yyy:3
```

**Comment by ccandito** [comment]
thanks
