### ISSUE TITLE
[Question] How to make retry to work after job failed

### ISSUE THREAD

**Issue by aliencrash** [OCA/queue#438]
How do I make the job queue to requeue after a job failure?

**Comment by sbidoul** [comment]
If the exception is a [RetryableJobError](https://github.com/OCA/queue/blob/c8b16ff73a85f72f8b84bbb17a774f44587be875/queue_job/exception.py#L21), queue_job will retry automatically.

**Comment by CasVissers-360ERP** [comment]
@aliencrash 
model.requeue_stuck_jobs(enqueued_delta=5, started_delta=5) should take care of that. See that I also added 5 minutes to started_delta to ensure started jobs are also requeued after a set time.
