### ISSUE TITLE
Wait for the result of the job

### ISSUE THREAD

**Issue by KamranValijonov** [OCA/queue#444]
**I am looking for an option to wait for result of parallel jobs.**
In my use case, I should not exit the function until all the `delayed` jobs are finished (which is currently finishing after the function returns). 
I have some experience with Celery, where I could wait for a result of jobs with the `some_delayed_job.result()`.
Could you please provide some insights on how I can achieve this functionality with `queue_job` ?

**Comment by sbidoul** [comment]
I'm afraid there is no way to do that as the jobs won't even start before the current transaction is committed.
