### ISSUE TITLE
`queue_job` : app icon 15.0 style

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/queue#457]
Hello, what do you think of these new icons for the `queue_job` module?
The current one doesn't have the new Odoo app icon style 

Current:
![current](https://github.com/OCA/queue/raw/14.0/queue_job/static/description/icon.png)

New option A:
![optionA](https://user-images.githubusercontent.com/1914185/187488088-a6612961-7b40-48ad-a7bf-83ec65989924.svg)

New option B:
![optionB](https://user-images.githubusercontent.com/1914185/187487658-54f3eefc-48e9-46e9-8e21-8073b1c6e635.svg)

@simahawk @guewen

**Comment by pedrobaeza** [comment]
Option A seems good to me.

**Comment by guewen** [comment]
Hey thanks! I like B personally 😄

**Comment by ivantodorovich** [comment]
I'm inclined for B too

**Comment by simahawk** [comment]
Thanks for the work! 
IMO the icon should give the idea of a "queue of things". The 2nd one gives only the idea of "configuration".

**Comment by guewen** [comment]
It gives me the idea of workers

**Comment by guewen** [comment]
Anyway, both would be fine

**Comment by pedrobaeza** [comment]
Merged, so closing.
