### ISSUE TITLE
User in cron-job needs read-right ir.cron document after install of queue_job_cron

### ISSUE THREAD

**Issue by whulshof** [OCA/queue#48]
Before installing queue_job_cron the user running the cron job could be anyone who had the access rights to the object of the job. After installing the user also needs read rights to ir.cron. This is irrespective of how the job is running, job_queue or not. Is this on purpose?

**Comment by guewen** [comment]
Hi,

~~I don't think it's on purpose, the job should be created with the user of the cron (sudo), here I guess:~~ edit: It's already the good user, not the issue

https://github.com/OCA/queue/blob/9331cb7aa5292a9eff5f607fa0161f99ae940216/queue_job_cron/models/ir_cron.py#L46

I don't think it's on purpose, maybe the job should be created as user admin, with the cron's user in arguments and sudo to it inside 

https://github.com/OCA/queue/blob/9331cb7aa5292a9eff5f607fa0161f99ae940216/queue_job_cron/models/ir_cron.py#L30

**Comment by sbidoul** [comment]
ping @Cedric-Pigeon

**Comment by sbidoul** [comment]
@whulshof see #56

**Comment by whulshof** [comment]
@sbidoul Thanks a lot!
