### ISSUE TITLE
[Question and proposal ] Whay there is no cron to perform pending jobs ?

### ISSUE THREAD

**Issue by chermed** [OCA/queue#5]
I try to test the queue module, it's a great ! thank you

My first remark is why there is not cron task to perform all jobs that are pending.

I think, it would be nice to pass the user in the delay method

**Comment by guewen** [comment]
There is no need to use a cron job, the jobs are automatically executed by the jobrunner. You have to use `--load=web,web_kanban,queue_job` and configure the `ODOO_QUEUE_JOB_CHANNELS` variable (see in the readme).

Normally, the user that creates the job is kept in the job and used when executed the job. If you need a different user, you have to do `recordset.sudo(user).with_delay().my_job()`. If you observe the user is not kept, please open an issue describing the issue.

**Comment by chermed** [comment]
@guewen thanks a lot, I will test more the module.
