### ISSUE TITLE
Disable queue_job in staging env

### ISSUE THREAD

**Issue by jgu-opennet** [OCA/queue#526]
Hello,

I have a question I was not able to find an answer in the doc.

Context:
A staging environment has no queue_job loaded as server_wide_module.
When duplicating the database from prod (contains queued jobs) will it cause stability issues in the staging env (apart from jobs not running) ?
empirically i could say it's safe but would be great to have an expert confirmation.

I also think that the installation documentation is lacking information about setting up queue_job in a multi database setup. I could make a PR to improve doc if you are interested?

Thank you

**Comment by guewen** [comment]
Hi, if the staging environment does not load queue_job in the server wide modules, jobs will not be executed at all in this env, so it's safe :+1: .

Regarding a PR, I'd say any help is welcome!
