### ISSUE TITLE
Question: Is it possible to modify an existing queue.job chain?

### ISSUE THREAD

**Issue by amh-mw** [OCA/queue#527]
Given that I have a large data migration with internal dependencies, it is simple enough to set up the initial chain., i.e. `chain(*[module.delayable().migration() for module in modules]).delay()` yielding `A -> B -> C -> D`.

Now let's say that C is a bit of a beast, and I would like to attack it in parallel, so at the point when C runs, I would like it to generate a new `group(chunk.delayable().migration() for chunk in migration.chunks)`, and graft that onto the original graph, yielding something like `A -> B -> C -> group(C1, C2, ...) -> D`.

It looks like I could use `Job.load` to load the job from the `queue.job` record, then call `add_depends`, but I'm not seeing how to serialize it back to the database. I'm a developer, so I'm happy to build out this piece for 15.0, once I'm convinced it isn't a terrible idea.

Criticism welcome.

**Comment by guewen** [comment]
Hi, once jobs are delayed (stored in DB), there is no way to change the dependencies.

I reckon you could find all  the graphs in database and find a way to update all the concerned jobs dependencies, but I'm not convinced it's a good idea ;)

Does something prevent you from generating a entirely new graph in Job C which does the last part of the chain `group(C1, C2, ...) => D` ?

**Comment by amh-mw** [comment]
That's a solid idea; I'm going to rework it such that I only generate one link of the chain at a time. Thanks!
