### ISSUE TITLE
[QUESTION] About channels 

### ISSUE THREAD

**Issue by esakarya** [OCA/queue#538]
Hi i have 3 connector i open sub channel inside root. I want each channel own one channel.
root.a
root.b
root.c

so my correct channel config is right ?
[queue_job]
channels = root:3, root.a:1, root.a:2,  root.a:3

also my this channel workers. comig from odoo's main workers config ? or its adding odoo's main workers ?
i want 4 worker for odoo, and 3 worker for channels

[odoo]
workers = 7

thats correct ?

**Comment by simahawk** [comment]
The best is to have a separated odoo instance that only runs jobs.
Regarding channel capacity: ` channels = root:3, root.a:1, root.b:1, root.c:1` looks good.
