### ISSUE TITLE
[14.0] identity_exact not working w/ chained jobs?

### ISSUE THREAD

**Issue by simahawk** [OCA/queue#552]
I have this piece of code
```py
        for rec in new_records:
            job1 = rec.delayable().action_exchange_generate()
            if not skip_send:
                # Chain send job
                job1.on_done(rec.delayable().action_exchange_send())
            job1.delay()
```
I inject `identity_key=identity_exact`  [here](https://github.com/OCA/edi/blob/4437f44f242a0a2a9ec232224563391735804e6c/edi_oca/models/edi_exchange_record.py#L565-L572).
 
Here I test that no duplicated job gets created but it does not work.
```py
    def test_job(self):
        with trap_jobs() as trap:
            self.backend._check_output_exchange_sync(record_ids=self.record.ids)
            trap.assert_jobs_count(2)
            trap.assert_enqueued_job(
                self.backend.exchange_record_model.action_exchange_generate,
            )
            trap.assert_enqueued_job(
                self.backend.exchange_record_model.action_exchange_send,
            )
            self.backend._check_output_exchange_sync(record_ids=self.record.ids)
            self.backend._check_output_exchange_sync(record_ids=self.record.ids)
            # identity key should prevent having new jobs
            trap.assert_jobs_count(2)
```
I have 6 jobs at the end while I expect to have still 2 jobs only.

I've inspected the identity keys of those jobs and they all match :thinking:  
I also checked if `job.job_record_with_same_identity_key` gets called: it is called but it cannot find the jobs.
Flushing does not help. 

I've created a silly server action to test the same piece of code via UI on the same record and gives me the same result...

Am I doing something wrong or we have a bug w/ chained jobs?

Side note: unless I'm mistaken I think `job.job_record_with_same_identity_key` does not search for all possible states when you have a job that is waiting for a dependency here https://github.com/OCA/queue/blob/199e9e4d43875ae722c91d4ef8795717473383ff/queue_job/job.py#L303

**Comment by simahawk** [comment]
I confirm that by removing the chain from the equation, it works:
```
job1 = rec.delayable().action_exchange_generate()
job1.delay()
```
This works fine in my server action and no extra job gets created.
At first sight I don't see why it shouldn't work w/ chained jobs.
@guewen any pointer?

**Comment by guewen** [comment]
Hi @simahawk, looks like #546?

**Comment by simahawk** [comment]
Ciao @guewen :wave: Ahhh! I missed that, thanks!

**Comment by simahawk** [comment]
@guewen in regards to #546 I'm not sure this change will solve the problem. What I see is that - in my case - both jobs are re-created, not only the one that is waiting. Which means that just adding `WAIT_DEPENDENCIES` won't be enough.
Am I wrong?

**Comment by guewen** [comment]
I would need to dive into the implementation and I won't be able now 😔

IIRC the idea was that identity keys on a graph is an all or nothing thing: if all the keys are identical, then the whole graph is discarded. Otherwise the graph is enqueued.

Hope that helps
