### ISSUE TITLE
Since Odoo 15.0 environment.manage is useless warning from migration script in queue_job

### ISSUE THREAD

**Issue by gdgellatly** [OCA/queue#555]
https://github.com/OCA/queue/blob/21e3532bbc5cf77d256ce883de6e7b3b0fc1a9f0/queue_job/migrations/15.0.1.1.0/post-migration.py#L11

Just saw it in upgrade warnings, no investigation.

**Comment by abdullahhabbal** [comment]
Same issue
any updates?
