### ISSUE TITLE
queue_job_cron_jobrunner for v13

### ISSUE THREAD

**Issue by matmicro** [OCA/queue#561]
Is there a chance to backport the module "queue_job_cron_jobrunner" for v13 ?

**Comment by simahawk** [comment]
That module works thanks to cron triggers (available from v15 on). I don't think you can work around that w/o coding your own thing.
@ivantodorovich ping :)

**Comment by ivantodorovich** [comment]
That's exactly right 😅 although it could be back ported with one very important limitation: without triggers you wouldn't get immediate job execution . There would be a delay until the cron is triggered by it's schedule

**Comment by simahawk** [comment]
Alternative to evaluate https://github.com/OCA/queue/pull/562
