### ISSUE TITLE
[Feature] Inmediate execution of jobs

### ISSUE THREAD

**Issue by yucer** [OCA/queue#60]
Suppose you want to make optionally **delayable** operations, and include those options in settings. 

Taking the [with_delay](https://github.com/OCA/queue/blob/221dd95366fd3ec7903b4726a2b5726ea5740e6b/queue_job/models/base.py#L38) sample, you'll end coding something like this:

```python
if myoptions.delay_user_write:
   self.env['res.users'].with_delay().write({'name': 'test'})
else:
   self.env['res.users'].write({'name': 'test'})
```

The *with_delay* or the old *delay* includes the feature of _logging_, _scheduling_ or _retrying_ an execution via the _job_ concept. 

One could think that the job creation has no sense without the scheduling part, but even when executed immediately it might include advantages. Not only _logging_ or _retrying_ the executions, also the ones that you are proposing for _checking duplicate execution_, and any other background / parallel working stuff that you might include. 

So here is a question: _Does it have sense a job without delaying ?_

I think the answer is _yes_.

Maybe the function could be named **as_job** instead of **with_delay** and include the boolean option **delay**. Some features like _retry_ could still work with immediate execution of those calls. 

_Optional_ delayed executions using the jobs is also useful for developing, because we would be able to try first the features with delayed=False and then enable it for deploying.

For me It is something like when the [odoo8-addon-cron-run-manually](https://pypi.python.org/pypi/odoo8-addon-cron-run-manually/8.0.1.0.0.99.dev5) was introduced. It was very useful. One could try the cron live and then activate the schedule for further executions.

**Comment by guewen** [comment]
I'd prefer to write this but that's not the point :)

```python
recordset = self.env['res.users']
if myoptions.delay_user_write:
    recordset = recordset.with_delay()
recordset.write({'name': 'test'})
```

Your idea is interesting, but the big difference between them is synchronous and asynchronous with  one case being done in the same transaction, another being done in another transaction.
If you don't delay but want to execute a function as a job, then how do you handle a retry? If the first try fails, it means you have to rollback the transaction, altogether with the transaction that called the "job without delay", so you can no longer retry it. It seems to me that if you want to benefit from those features, you are forced to execute the job in another transaction, which means asynchronous and we're back to the `with_delay`.

**Comment by guewen** [comment]
Would the PR https://github.com/OCA/queue/pull/111 answer to your needs?

**Comment by yucer** [comment]
Thank you for keeping track of this. Sorry for the late reply.

Not really. That PR #111 solves the difficulties during debug, but we still lost the "logging" part.

From the user perspective the jobs are just tasks to do. Also in prod one might have two contexts were the task should be done directly, and some of them when the job should be queued. Nevertheless, the admin might want to check the completed jobs to see if some task was performed.

**Comment by yucer** [comment]
> Your idea is interesting, but the big difference between them is synchronous and asynchronous with one case being done in the same transaction, another being done in another transaction.

I understand that the asynchronous nature of the task was the motivation to conceptualize the *job*. And also that you have the principle that says: "all synchronous without transactions, all asynchronous with transactions". it might be that the principle is too hard ?

I mean I could need synchronous tasks within a transaction, and asynchronous tasks might not been forced to one. That's depending of the nature of the problem, i guess.

Might that be an optional parameter (the current behavior can be kept as default) ? Does it sound like a non-sense ?

There is also an intermediate solution, for those that were not executed inside a transaction the retry can be disabled. The related action might have still sense.
