### ISSUE TITLE
[QUESTION][16.0] queue_job: How to run parallel queue

### ISSUE THREAD

**Issue by Saran440** [OCA/queue#626]
I tested with module `queue_job` and `base_import_async`
and config odoo.conf

```
workers = 4
server_wide_modules = web,queue_job

[queue_job]
channels = root:4,root.ir_cron:3
```

**Test 1** (Import 2 file 100k and 50k) with run background
- Import 100k record first. status = 'started'
- Import 50k record. status = 'started' but it taketime 87s
![Selection_003](https://github.com/OCA/queue/assets/20896369/5f792338-c4e2-4ed0-ac6b-45604f17ae6a)

**Test 2** (Import 1 file 50k) with run background
- Import 50k record. status = 'started' it taketime 26s
![Selection_004](https://github.com/OCA/queue/assets/20896369/ebc7e0aa-3e8c-43dd-b19e-f3a8e038fa04)

I would like to run 2 file in parallel queue. How can I config or do something mistake?

Thank you

**Comment by SGmuwa** [comment]
I have the same issue
