### ISSUE TITLE
[10.0] queue_job: default_channel argument seems to not work

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/queue#64]
I have this job with `default_channel` argument:

https://github.com/OCA/l10n-spain/blob/3baa28b44211fc34516ebe87b9068204231bff47/l10n_es_aeat_sii/models/account_invoice.py#L1389

and this is how it's called:

https://github.com/OCA/l10n-spain/blob/3baa28b44211fc34516ebe87b9068204231bff47/l10n_es_aeat_sii/models/account_invoice.py#L964

But the channel of the jobs is `root`, not the one I'm putting. Do you know why?

**Comment by guewen** [comment]
Was the job already existing in the database before you added the `default_channel` or is it happening an a fresh database?

**Comment by pedrobaeza** [comment]
Well, it's not a fresh database, but a fresh job, that is created after confirming the invoice in the code in the second line (https://github.com/OCA/l10n-spain/blob/3baa28b44211fc34516ebe87b9068204231bff47/l10n_es_aeat_sii/models/account_invoice.py#L964)

**Comment by pedrobaeza** [comment]
@guewen any news about this?

**Comment by guewen** [comment]
No I couldn't have a look at it :sob:

**Comment by lmignon** [comment]
@pedrobaeza Is your channel declared/configured into odoo.cfg or on the command line? Is your channel listed into the list of available channels?

**Comment by guewen** [comment]
I confirm the automatic registration of job functions and default channels is no longer working with #49 and #50.

**Comment by guewen** [comment]
Working on a patch.

**Comment by pedrobaeza** [comment]
Great, thanks!

**Comment by guewen** [comment]
@pedrobaeza did you encounter the issue in 10.0 or 11.0? 
I expect the 10.0 one to works, and the 11.0 failing due to this difference between py2 and py3: https://github.com/OCA/queue/pull/69#issuecomment-391031382

And indeed I couldn't reproduce on 10.0

**Comment by pedrobaeza** [comment]
Thanks for the following-up, Guewen. I found the problem in v10. The line I mentioned (https://github.com/OCA/l10n-spain/blob/3baa28b44211fc34516ebe87b9068204231bff47/l10n_es_aeat_sii/models/account_invoice.py#L964), was for this module in v10: https://github.com/OCA/l10n-spain/tree/10.0/l10n_es_aeat_sii, so there should be something different there.

Tell me if you need that I do any test.

**Comment by guewen** [comment]
I installed l10n_es_aeat_sii from the branch 10.0, and the latest commit of the branch 10.0 of oca/queue, the channels have been created and properly assigned to the job function:

![selection_294](https://user-images.githubusercontent.com/417223/40408873-4f44188e-5e69-11e8-9b0a-2ed513bddcc6.png)

**Comment by pedrobaeza** [comment]
Seeing my instances, I don't have the functions on that channels:

![seleccion_014](https://user-images.githubusercontent.com/7165771/40409081-f6451282-5e69-11e8-99fc-da4f59e2b6cf.png)

What can be the problem? The code is updated (our Docker + module_auto_update system handles that), so I don't understand what can be. Are these functions registered only once or each time I restart the server?

**Comment by guewen** [comment]
@pedrobaeza only once at registry loading, and if they are created without `default_channel` the first time, they'll keep the `root` channel. You can try to delete the "queue.job.function" rows and they'll be recreated on the registry load, so you can check if the channel is set correctly.

**Comment by pedrobaeza** [comment]
OK, that's it! It seems that I install the module with a code version that lacks this and this has remained meanwhile (or maybe there's a problem in installation time...). For now, I'm closing this, and if I observe there's a different behavior on installation than when running afterwards, I'll report back.

Thanks for the support.
