### ISSUE TITLE
OSError: [WinError 10038] An operation was attempted on something that is not a socket

### ISSUE THREAD

**Issue by lgarcia11** [OCA/queue#65]
This line https://github.com/OCA/queue/blob/11.0/queue_job/jobrunner/runner.py#L403 is throwing the exception "An operation was attempted on something that is not a socket"

**Comment by lgarcia11** [comment]
Maybe this can help,
https://stackoverflow.com/questions/35889267/an-operation-was-attempted-on-something-that-is-not-a-socket-tried-fixing-a-lot

**Comment by guewen** [comment]
What OS do you use?

**Comment by lgarcia11** [comment]
@guewen The error is happening on Windows 10 64-bit,
I also tested on Ubuntu 16.04 but there everything was right.
Thanks

**Comment by guewen** [comment]
Ok. I'd really recommend you to work on a linux system (or using a linux Docker image in your windows).

If you have a fix for this, we can consider to merge it but I don't know anyone who actually can/want to support Windows.

**Comment by lgarcia11** [comment]
Thanks, yes I think that I will move the work to a Linux system.
I haven't found a fix yet :(  maybe in the meantime the documentation should say that Windows is not working and save some time to future developers.

**Comment by guewen** [comment]
> the documentation should say that Windows is not working and save some time to future developers.

Could you propose a PR in this regard?
