### ISSUE TITLE
Queue.job stucked in pending.

### ISSUE THREAD

**Issue by NicolasGlezGlez** [OCA/queue#711]
Hi all, I use docker with doodba and I am trying to configure in the devel.yaml to be able to generate work queues, I manage to generate them with the function with_delay() but they stay in pending indefinitely and I am quite convinced that it is a configuration issue.

Inside enviroment I have:
ODOO_QUEUE_JOB_CHANNELS: ‘root:4’

and in command I have:
      --workers=4
      --dev=reload,qweb,web,queue_job,werkzeug,xml

I think I'm not missing anything but I'm not sure. Thanks for your time!

**Comment by pedrobaeza** [comment]
You are missing the `--load=web,queue_job` parameter.

**Comment by NicolasGlezGlez** [comment]
> You are missing the `--load=web,queue_job` parameter.

My god, 3 hours xDD I think put in --dev was enough, thx a lot Pedro
