### ISSUE TITLE
Is it possible to force synchronous execution during tests?

### ISSUE THREAD

**Issue by ecino** [OCA/queue#89]
With some functions being called inside jobs (with_delay), automated testing becomes harder. Is there a feature to enforce synchronous call while we are running tests?

**Comment by guewen** [comment]
In version 9.0 I wrote this, which transforms a job in a synchronous function: https://github.com/OCA/connector/blob/caee9b08818f550d18bf0193e21ae3abb3d3c632/connector/tests/common.py#L28-L64

The API has changed so it won't work as is, but a similar idea could be applied.

Now generally I prefer to split the tests in different units:

* one test will replace the job by a mock and test that it's called with the arguments we need
* one different test will directly call the job method (synchronously) and check the result

**Comment by guewen** [comment]
This one should please you https://github.com/OCA/queue/pull/111

**Comment by simahawk** [comment]
better this one https://github.com/OCA/queue/pull/114 I should get back to #111 actually :innocent:
