### ISSUE TITLE
[11.0] Queue cron job eta?

### ISSUE THREAD

**Issue by GSLabIt** [OCA/queue#90]
any eta to port `queue_cron_job` to 11? Thx

**Comment by lmignon** [comment]
@joezsweet feel free to do the port. TOpensource can only work if there are enough people contributing to it. When we develop a module and publish it we always hope to share the cost of its maintenance while enriching it with the experience of other users/developers. The evolution therefore depends on the needs and the capacity to be funded to do this work. 
You are welcome to make this migration we will be happy to support you in this work by reviewing your code.

**Comment by GSLabIt** [comment]
Thx for the answer, thought someone was already working on that. 

That said, I'm not yet that experienced to contribute, but I'll sure try to port it asap!!

**Comment by guewen** [comment]
@GSLabIt your test and review on https://github.com/OCA/queue/pull/117 would be appreciated.
