### ISSUE TITLE
[11.0] Concurrent Update Error

### ISSUE THREAD

**Issue by Gokulakannanaj** [OCA/queue#91]
I have 10 Jobs. First two jobs are started and one throws the concurrent error. It repeated to every job.
Two jobs are started simultaneously.
 How can i prevent another one is pending if one job is running? 
But my local it works properly. When my code move from local to remote i face the above concurrent issues.

**Comment by sbidoul** [comment]
You need to enqueue your jobs in a channel of capacity 1

**Comment by Gokulakannanaj** [comment]
I saw the document. They said to put ODOO_QUEUE_JOB_CHANNELS=root:1.
How can i give this while starting the server and My changed ODOO server configuration file not updated.
This situation what can i do ?

**Comment by sbidoul** [comment]
If you prefer you can configure the channels in your `odoo.cfg`, as explained in the [README](https://github.com/OCA/queue/tree/11.0/queue_job#configuration).

**Comment by Gokulakannanaj** [comment]
[Performance Issues]

When i changed from root:2 to root:1 , My CPU usage cross the 80 - 85%(closer to last job) for two users only.
When users limit exceed (more than 5) server stopped.
How can i prevent it ?

For ex.
100 Jobs are in pending state. CPU Usage goes 5-10% (Upto 80 Jobs). But after cross 80 CPU Usages exceed 80 - 90 (100 Jobs are doing same action for different users)

**Comment by Gokulakannanaj** [comment]
Hi @sbidoul after change the channel capacity 1, process run normally and i cannot get any concurrent error in my local machine. But In server side, i'm getting the concurrent error repeatedly.  Even if i requeue the process, again getting concurrent issue. Now in my situation, Performance not a issue.
If workers is 0, what happened that time ?
I need your help @sbidoul @guewen ?
[In my production i have 4 servers and channel capacity 1]
